In [2]:
import pandas as pd

df = pd.read_csv('../data/raw/co2.csv')

In [3]:
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [6]:
df = df.rename(columns={
    'Vehicle Class': 'Vehicle_type',
    'Engine Size(L)': 'Engine_Size_L',
    'Fuel Type': 'Fuel_Type',
    'Fuel Consumption Comb (L/100 km)': 'Fuel_Consumption_Comb_L_per_100_km',
    'CO2 Emissions(g/km)': 'CO2_Emissions_g_per_km'
})
df

,Make,Model,Vehicle_type,Engine_Size_L,Cylinders,Transmission,Fuel_Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel_Consumption_Comb_L_per_100_km,Fuel Consumption Comb (mpg),CO2_Emissions_g_per_km
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [7]:
features = [
    'Engine_Size_L', 'Cylinders', 'Transmission', 
    'Fuel_Type', 'Fuel_Consumption_Comb_L_per_100_km', 'Vehicle_type'
]
target = 'CO2_Emissions_g_per_km'

x = df[features]
y = df[target]

In [9]:
x

,Engine_Size_L,Cylinders,Transmission,Fuel_Type,Fuel_Consumption_Comb_L_per_100_km,Vehicle_type
0,2.0,4,AS5,Z,8.5,COMPACT
1,2.4,4,M6,Z,9.6,COMPACT
2,1.5,4,AV7,Z,5.9,COMPACT
3,3.5,6,AS6,Z,11.1,SUV - SMALL
4,3.5,6,AS6,Z,10.6,SUV - SMALL
...,...,...,...,...,...,...
7380,2.0,4,AS8,Z,9.4,SUV - SMALL
7381,2.0,4,AS8,Z,9.9,SUV - SMALL
7382,2.0,4,AS8,Z,10.3,SUV - SMALL
7383,2.0,4,AS8,Z,9.9,SUV - STANDARD
7384,2.0,4,AS8,Z,10.7,SUV - STANDARD

In [10]:
y

0       196
1       221
2       136
3       255
4       244
       ...
7380    219
7381    232
7382    240
7383    232
7384    248
Name: CO2_Emissions_g_per_km, Length: 7385, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

cat_features = ['Transmission', 'Fuel_Type', 'Vehicle_type']
num_features = ['Engine_Size_L', 'Cylinders', 'Fuel_Consumption_Comb_L_per_100_km']

preprocessor = ColumnTransformer(
    transformers = [
        ('num', 'passthrough', num_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_features)
])
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
X_train

,Engine_Size_L,Cylinders,Transmission,Fuel_Type,Fuel_Consumption_Comb_L_per_100_km,Vehicle_type
6590,3.0,6,AS8,Z,9.9,SUBCOMPACT
6274,4.0,6,A5,X,12.7,PICKUP TRUCK - SMALL
2251,3.0,6,M6,Z,11.7,COMPACT
3149,3.4,6,AM7,Z,9.8,TWO-SEATER
4362,2.0,4,AS8,Z,8.7,STATION WAGON - MID-SIZE
...,...,...,...,...,...,...
5191,2.0,4,M6,Z,9.0,SUBCOMPACT
5226,3.5,6,AV7,X,9.1,MID-SIZE
5390,3.5,6,AS8,X,10.4,SUV - STANDARD
860,2.5,4,AV,X,8.6,SUV - SMALL
7270,4.0,8,AM8,Z,11.9,FULL-SIZE

In [15]:
X_test

,Engine_Size_L,Cylinders,Transmission,Fuel_Type,Fuel_Consumption_Comb_L_per_100_km,Vehicle_type
7261,3.0,6,AM8,Z,10.9,FULL-SIZE
4489,4.4,8,AM7,Z,14.7,SUBCOMPACT
1539,6.2,8,A8,Z,14.0,PICKUP TRUCK - STANDARD
3532,5.3,8,A6,X,12.7,PICKUP TRUCK - STANDARD
6418,4.0,6,AS5,X,13.2,SUV - STANDARD
...,...,...,...,...,...,...
7185,2.0,4,A9,Z,9.5,SUBCOMPACT
1740,2.0,4,AS6,X,11.3,SUV - SMALL
4609,1.4,4,AS6,X,7.8,STATION WAGON - SMALL
1844,3.5,6,AS7,Z,10.2,MID-SIZE
5154,2.0,4,AM7,Z,8.2,COMPACT

In [16]:
import joblib

# Criar o pipeline que processa e treina
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
])

# Treinar o modelo
model_pipeline.fit(X_train, y_train)

# (Opcional) Avaliar métricas de regressão (RMSE, MAE)
from sklearn.metrics import mean_absolute_error, r2_score
preds = model_pipeline.predict(X_test)
print(f"R2 Score: {r2_score(y_test, preds)}")
print(f"MAE: {mean_absolute_error(y_test, preds)} g/km")

# Salvar o modelo treinado (O ÚNICO artefato exigido)
joblib.dump(model_pipeline, '../ml/models/co2_baseline_model.pkl')

R2 Score: 0.996429065879812
MAE: 1.9034969967008641 g/km

['../ml/models/co2_baseline_model.pkl']

In [17]:
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Features SEM consumo de combustível
features = [
    'Engine_Size_L',
    'Cylinders',
    'Transmission',
    'Fuel_Type',
    'Vehicle_type'
]

target = 'CO2_Emissions_g_per_km'

# Separar X e y
X = df[features]
y = df[target]

# Separar categóricas e numéricas
cat_features = ['Transmission', 'Fuel_Type', 'Vehicle_type']
num_features = ['Engine_Size_L', 'Cylinders']

# Preprocessamento
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', num_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_features)
    ]
)

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Pipeline completa
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(
        n_estimators=200,
        max_depth=15,
        random_state=42,
        n_jobs=-1
    ))
])

# Treinar
model_pipeline.fit(X_train, y_train)

# Predições
preds = model_pipeline.predict(X_test)

# Métricas
r2 = r2_score(y_test, preds)
mae = mean_absolute_error(y_test, preds)

print(f"R2 Score: {r2}")
print(f"MAE: {mae} g/km")

# Salvar modelo
joblib.dump(
    model_pipeline,
    '../ml/models/co2_model_without_fuel_consumption.pkl'
)

R2 Score: 0.9303714085442931
MAE: 11.061718682781224 g/km

['../ml/models/co2_model_without_fuel_consumption.pkl']